[package]
name = "spotifyexp"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]
edition = "2018"

[dependencies]
reqwest = "~0.11.3"
tokio = { version = "1.6.1", features = ["macros"] }
